version: "3.8"

services:
  quotes:
    build:
      context: .
      dockerfile: Dockerfile
    image: quotes:latest
    ports:
      - 40011:3000
    environment:
      - SECRET_KEY=5f154f355b9f70d73d0810686fdc7d1f22f1bfee06c78b115cb579d45733282a
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped