version: '3.8'

services:
  homecookeds_revenge:
    build: .
    image: homecookeds_revenge
    privileged: true    
    ports:
      - "40025:8001"      
    environment:
      - FLAG=bctf{y0ur_b4s1c_s0lv35_h4v3_n0_pl4c3_h3r3}      
    restart: unless-stopped